import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "@next/font/local";

const ginto = localFont({
  src: [
    {
      path: "../public/fonts/ginto.otf",
      weight: "normal",
    },
  ],
  variable: "--font-ginto",
});

const ggSans = localFont({
  src: [
    {
      path: "../public/fonts/gg sans Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/gg sans Regular.ttf",
      weight: "normal",
    },
    {
      path: "../public/fonts/gg sans Bold.ttf",
      weight: "bold",
    },
  ],
  variable: "--font-ggsans",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${ginto.variable} ${ggSans.variable} font-ggsans`}
      >
        {children}
      </body>
    </html>
  );
}
